rootProject.name = "LookARound"
include(":app")
include(":core")
include(":core-android")
include(":core-android-model")
include(":repo-nominatim")
include(":repo-overpass")
include(":repo-photon")
include(":ui-camera")
include(":ui-main")
include(":ui-map")
include(":ui-place-list")
include(":ui-place-types")
include(":ui-search")
