rootProject.name = "LookARound"
include(":app")
include(":core")
include(":core-android")
include(":repo-nominatim")
include(":repo-overpass")
include(":repo-photon")
include(":tangram")
include(":ui-about")
include(":ui-camera")
include(":ui-main")
include(":ui-map")
include(":ui-place-list")
include(":ui-place-map-list")
include(":ui-place-categories")
include(":ui-recent-searches")
include(":ui-settings")
