include(":ui-place-types")
include(":repo-photon")
include(":core-android")
include(":ui-map")
include(":repo-nominatim")
rootProject.name = "LookARound"
include(":repo-overpass")
include(":app")
include(":core")
include(":ui-main")
